#!/usr/bin/env python3
"""Freeze a slice of real night scores plus this assembler's output as a test fixture.

The Kotlin and Python assemblers are the same algorithm written twice, and nothing
stops them drifting apart - a drift that would silently invalidate every tuned
threshold, because the phone would no longer behave like the thing that was tuned.
The Kotlin test suite replays this fixture and asserts identical events.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from assembler import DEFAULT_PARAMS, assemble
from eval_night import load_nights
from frontend import CLASSES, ROOT

OUT = ROOT / "android/core-domain/src/test/resources/parity_fixture.json"


def main() -> None:
    nights, _ = load_nights(ROOT / "ml/artifacts/nights.npz")
    scores, rms, _ = nights[0]

    # A window with real activity in it - an all-silence slice would prove nothing.
    activity = scores[:, :3].max(axis=1)
    centre = int(np.argmax(np.convolve(activity, np.ones(200) / 200, mode="same")))
    lo = max(0, centre - 300)
    hi = min(len(scores), lo + 600)
    s = scores[lo:hi]
    r = rms[lo:hi]

    events = assemble(s, r, DEFAULT_PARAMS)
    fixture = {
        "description": "Generated by ml/parity_fixture.py; replayed by AssemblerParityTest.",
        "hop_ms": 480,
        "classes": CLASSES,
        "params": {k: DEFAULT_PARAMS[k] for k in DEFAULT_PARAMS},
        "scores": [[round(float(x), 6) for x in row] for row in s],
        "rms_db": [round(float(x), 4) for x in r],
        "expected_events": [
            {
                "cls": e.cls,
                "start_ms": e.start_ms,
                "end_ms": e.end_ms,
                "peak_score": round(e.peak_score, 5),
                "peak_frame_ms": e.peak_frame_ms,
            }
            for e in events
        ],
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(fixture, indent=1))
    print(f"wrote {OUT}")
    print(f"  {len(s)} frames, {len(events)} expected events: "
          f"{ {c: sum(1 for e in events if e.cls == c) for c in ('COUGH','SNEEZE','SNORE')} }")


if __name__ == "__main__":
    main()
