#!/usr/bin/env bash
# Sets up api.hamanhealth.com as a reverse proxy to haman-api (127.0.0.1:8002)
# via DirectAdmin's CustomBuild / LiteSpeed or Apache.
#
# Run on the server as root AFTER:
#   1. api.hamanhealth.com DNS A record points to 128.140.54.86
#   2. The domain is created in DirectAdmin (even as a pointer/addon)
#
# Usage: bash deploy/directadmin-proxy-setup.sh

set -euo pipefail

DA_DOMAIN="api.hamanhealth.com"
PROXY_TARGET="http://127.0.0.1:8002"

# ── Detect web server ─────────────────────────────────────────────────────────
if systemctl is-active --quiet lsws 2>/dev/null; then
  WEB_SERVER="litespeed"
elif systemctl is-active --quiet httpd 2>/dev/null; then
  WEB_SERVER="apache"
else
  echo "Could not detect running web server (lsws or httpd). Exiting."
  exit 1
fi

echo "Detected web server: $WEB_SERVER"

# ── LiteSpeed / OpenLiteSpeed ─────────────────────────────────────────────────
if [ "$WEB_SERVER" = "litespeed" ]; then
  # DirectAdmin + LiteSpeed stores per-domain extra config here:
  DA_CONF_DIR="/usr/local/directadmin/data/users"
  # Find the user who owns api.hamanhealth.com (usually the main DA user)
  DA_USER=$(grep -r "api.hamanhealth.com" "$DA_CONF_DIR" --include="domains.list" -l 2>/dev/null \
    | head -1 | awk -F/ '{print $8}' || true)

  if [ -z "$DA_USER" ]; then
    echo "Domain api.hamanhealth.com not found in DirectAdmin."
    echo "Please create it first in DirectAdmin → Domain Setup → Add Domain."
    echo "Then re-run this script."
    exit 1
  fi

  VHOST_CONF="/usr/local/directadmin/data/users/$DA_USER/domains/${DA_DOMAIN}.conf"
  cat > "$VHOST_CONF" <<LSEOF
# Haman Health API — reverse proxy to Docker container
# Auto-generated by deploy/directadmin-proxy-setup.sh

RewriteEngine On
ProxyPreserveHost On
ProxyPass / $PROXY_TARGET/
ProxyPassReverse / $PROXY_TARGET/
LSEOF

  echo "LiteSpeed vhost config written to $VHOST_CONF"
  echo "Restarting LiteSpeed..."
  /usr/local/lsws/bin/lswsctrl restart
fi

# ── Apache (httpd) ────────────────────────────────────────────────────────────
if [ "$WEB_SERVER" = "apache" ]; then
  CONF_FILE="/etc/httpd/conf.d/${DA_DOMAIN}.conf"
  cat > "$CONF_FILE" <<APACHEEOF
<VirtualHost *:80>
    ServerName ${DA_DOMAIN}
    RewriteEngine On
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]
</VirtualHost>

<VirtualHost *:443>
    ServerName ${DA_DOMAIN}
    SSLEngine on
    # Certbot fills these:
    # SSLCertificateFile    /etc/letsencrypt/live/${DA_DOMAIN}/fullchain.pem
    # SSLCertificateKeyFile /etc/letsencrypt/live/${DA_DOMAIN}/privkey.pem

    ProxyPreserveHost On
    ProxyPass        / ${PROXY_TARGET}/
    ProxyPassReverse / ${PROXY_TARGET}/

    ErrorLog  /var/log/httpd/${DA_DOMAIN}-error.log
    CustomLog /var/log/httpd/${DA_DOMAIN}-access.log combined
</VirtualHost>
APACHEEOF

  echo "Apache vhost written to $CONF_FILE"
  systemctl reload httpd
fi

# ── SSL ───────────────────────────────────────────────────────────────────────
echo ""
echo "Next step — get SSL certificate:"
echo "  certbot --${WEB_SERVER} -d ${DA_DOMAIN} --non-interactive --agree-tos -m r.reza2011@gmail.com"
echo ""
echo "Then test: curl https://${DA_DOMAIN}/api/health"
